### ISSUE TITLE
Making frontai open source

### ISSUE THREAD

**Issue by TchiRubick** [frontaid/examples#4]
# Great tools

This project is awesome. 

Would like to ask if it's possible to make [frontaid](https://frontaid.io/) fully open source ?  
This project fit very well my needs but I'm worried that it can go down soon as no no new commit on this account recently. I would like to be part of the contributor. Is it planned in the future ?

**Comment by frontaid** [comment]
Thank you! Currently, it is not planned to make FrontAid CMS open source. If being open source is important to you, maybe https://github.com/thinkmill/keystatic offers what you need. Please let me know what you think of it.
